---
### container
container_log_driver: journald

### common
aap_volumes_dir: '{{ ansible_user_dir }}/aap'
archive_compressed_extension: "tar.gz"
archive_decompressed_extension: "tar"
db_compressed_extension: db.gz
db_decompressed_extension: db
client_request_timeout: 30
# ^this should be the same as gateway_nginx_read_timeout, because that's how long a request may take after the jwt is injected


### backup/restore
gateway_use_archive_compression: "{{ use_archive_compression | default(true) }}"
gateway_use_db_compression: '{{ use_db_compression | default(false) }}'

### envoy
envoy_conf_dir: '{{ aap_volumes_dir }}/gatewayproxy/etc'
envoy_disable_https: false
envoy_http_port: 80
envoy_https_port: 443
envoy_request_timeout: '{{ (([(client_request_timeout | int), 10] | max) / 2) | int }}'


### automation gateway proxy
gateway_proxy_firewall_zone: public

### nginx
gateway_nginx_conf_dir: '{{ aap_volumes_dir }}/gateway/nginx/etc'
gateway_nginx_disable_https: false
gateway_nginx_disable_hsts: false
gateway_nginx_hsts_max_age: 63072000
gateway_nginx_http_port: 8083
gateway_nginx_https_port: 8446
gateway_nginx_https_protocols:
  - TLSv1.2
  - TLSv1.3
gateway_nginx_client_max_body_size: 5m
gateway_nginx_user_headers: []
gateway_nginx_read_timeout: '{{ (([(client_request_timeout | int), 10] | max) / 2) | int }}'


### automation gateway
gateway_container_requires: []
gateway_conf_dir: '{{ aap_volumes_dir }}/gateway/etc'
gateway_firewall_zone: public
gateway_admin_user: admin
gateway_admin_email: admin@example.com
gateway_uwsgi_port: 8052
gateway_uwsgi_timeout: '{{ (([(client_request_timeout | int), 10] | max) / 3) | int }}'
gateway_uwsgi_timeout_grace_period: 2
gateway_uwsgi_processes: '{{ ansible_processor_vcpus | default(4) | int * 2 + 1 }}'
gateway_uwsgi_listen_queue_size: 4096
gateway_control_plane_port: 50051
gateway_extra_settings: []
gateway_jwt_expiration_buffer_in_seconds: '{{ (([(client_request_timeout | int), 10] | max) / 2) | int }}'

### database
gateway_pg_username: gateway
gateway_pg_database: gateway
gateway_pg_port: 5432
gateway_pg_sslmode: prefer
gateway_pg_cert_auth: false

### redis
gateway_redis_cache_db: 4
gateway_redis_disable_tls: false
gateway_redis_port: 6379
gateway_redis_username: gateway

### GRPC
gateway_grpc_server_processes: 5
gateway_grpc_server_max_threads_per_process: 10
gateway_grpc_auth_service_timeout: '{{ (([(client_request_timeout | int), 10] | max) / 2) | int }}s'
# when grpc times out, users start to see 502s, indicating we need to horizontally scale GRPC.

### supervisor
supervisor_run_dir: '{{ aap_volumes_dir }}/gateway/supervisor/run'

### TLS CA
ca_trust_bundle: /etc/pki/tls/certs/ca-bundle.crt
...
